management:
  endpoints:
    web:
      exposure:
        include: health

email:
  gateway:
    sendgrid:
      base-url: https://api.sendgrid.com/v3
      api-key: ${SENDGRID_API_KEY}
    mailgun:
      base-url: https://api.mailgun.net/v3/sandbox3793fb4e82f6408281f7901e8578d9fc.mailgun.org
      api-key: ${MAILGUN_API_KEY}